spring:
  application:
    name: mybatis
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
